## https://docs.docker.com/config/daemon/prometheus/#configure-and-run-prometheus

global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['host.docker.internal:9090']

  - job_name: 'docker'
    static_configs:
      - targets:
          - host.docker.internal:9323
          - cadvisor:8080
          - memcached-exporter:9150
          - postgres-exporter:9187
